#!/bin/bash

set -e

: ${DEBUG:=1}
: ${TEMP_DIR:=exploded}

debug() {
    [[ "$DEBUG" ]] && echo "[DEBUG] $@" 1>&2
}


create_tar() {
  declare dockerImage=${1:? "required: docker image name as 1. parameter"}

  local id=$(docker run -itd --entrypoint=/bin/sh $dockerImage)
  local exportedImage=container.tar
  
  debug "container id=$id"

  docker export $id > $exportedImage
  debug "container is exported as: $exportedImage"

  docker rm -f $id &>/dev/null && debug "docker container is deleted: $id" || debug "container couldnt be deleted: $id"
}

main() {
    #docker build -t lalyos/kontainer .
    create_tar "$@"
    docker build -t kont -f Dockerfile.kontainer .
    docker run kont cat /go/src/scratch/kontainer > kontainer-$1
    chmod +x kontainer-$1
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
